"""Add chaotic_seed to Video

Revision ID: 292c81a8186a
Revises: 
Create Date: 2025-06-05 09:23:31.640357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '292c81a8186a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chaotic_seed', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_column('chaotic_seed')

    # ### end Alembic commands ###
